version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./GitPRism/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - gitprism-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  redis:
    image: redis:7
    container_name: gitprism-redis
    ports:
      - "6379:6379"
    networks:
      - gitprism-network
    restart: always
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s


  flyway:
    image: flyway/flyway:11.4.0
    container_name: flyway-migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - FLYWAY_USER=${MYSQL_USER}
      - FLYWAY_PASSWORD=${MYSQL_PASSWORD}
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: ["migrate"]
    networks:
      - gitprism-network
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: always
    depends_on:
      flyway:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
    networks:
      - gitprism-network

volumes:
  db_data:

networks:
  gitprism-network:
    name: gitprism-network
